Issue 12: Initial implementation of RS256 algorithm
iain-logan/jwt pull request #14
Opened 2017-03-28 15:55 UTC by jotsif

RS256 implementation

2017-04-02 17:56 UTC, iain-logan requested changes
Really appreciate the pull request, just a few tiny stylistic changes I'd like you to make. Thanks!

2017-04-02 17:56 UTC, iain-logan commented on src/test/scala/io/igl/jwt/JwtSpec.scala
> +    val pkbase64 = Base64.decodeBase64(pk)
I'm not so keen on the names `pk` and `pkbase64`, as we've just applied `decodeBase64` to _decode_ the base 64 encoded private key.

Basically, the variable names are the wrong way round.

Don't be afraid to use `privateKey` over `pk` as a name, it makes it more readable.
Short names don't buy us anything here.

2017-04-02 17:56 UTC, iain-logan commented on src/test/scala/io/igl/jwt/JwtSpec.scala
> +    DecodedJwt.validateEncodedJwtWithEncodedSecret(
Super picky here, but please add a blank line between declaring the values and validating the JWT to match the other tests.

2017-04-03 14:05 UTC, jotsif commented
Variables renamed and newline added.

2017-04-08 19:11 UTC, merged

2017-04-08 19:11 UTC, iain-logan commented
Thanks, pull request accepted

2017-04-10 06:04 UTC, jotsif commented
Thanks @iain-logan !